### PR TITLE
Fixed broken link to documentation

### PR DESCRIPTION
**Pull request by FilippoRezzonico**
Changed a broken link with a working one pointing to our documentation

### CODE REVIEW

**Comment by fredmaggiowski** [comment]
Failing tests could be related to this certificate being expired: https://github.com/mia-platform/custom-plugin-lib/pull/84/files ?

**Comment by chiararelandini** [comment]
@fredmaggiowski I think I’ve used the option of 3580000 days which should be approximately 10000 years

**Comment by davidebianchi** [comment]
It seems ca.crt end date is 31 Mar 2021, so it is the expired cert.

Other certs expire around 3 May 3001.

It is possible to use something like: https://github.com/jfromaniello/selfsigned?
I don't know if it is supported the generation from ca.

**Comment by chiararelandini** [comment]
@davidebianchi I am not sure. The `ca` tls option is not mandatory, however the connection on https throws an error if the certificate is self-signed and it is not explicitly allowed. Maybe it is enough to add the environment variable NODE_TLS_REJECT_UNAUTHORIZED='0' and take out the `ca` option. https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain

**Review by davidebianchi — APPROVED** [review]

**Pull request merged**
